services:
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    env_file:
      - ./backend/back.env
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: fracttal_user
      POSTGRES_PASSWORD: fracttal_password
      POSTGRES_DB: fracttal_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/1init.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2data.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
